name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
